import os

DATA_FOLDER="data/input"

ALGO_VERSION = '0.4.1'
CONTROL_PLANE_URL = os.environ['CONTROL_PLANE_URL']
DV_CAGE_ID = os.environ['DV_CAGE_ID']
SECRET_MANAGER_URL = os.environ['SECRET_MANAGER_URL']